### PR TITLE
Increase the stack trace

### PR DESCRIPTION
**Pull request by tatianacv**
Increase the stack trace on python ML testing.

### CODE REVIEW

**Review by khatchad — CHANGES_REQUESTED** [review]
Temporarily add the build failure.

**Comment by tatianacv** [comment]
I have added it.

**Comment by khatchad** [comment]
Looks like the exception was being swallowed, which is why we are not seeing a root cause: https://github.com/ponder-lab/ML/commit/46151a88ecdf5bccac97593c868787f2a75df772

**Comment by khatchad** [comment]
Here is the new info: https://app.travis-ci.com/github/ponder-lab/ML/builds/263091773#L41438-L41445

**Pull request merged**
