### PR TITLE
Fine logging

### PR DESCRIPTION
**Pull request by khatchad**
Instead of commented out output. But, the fine logging does not appear on the CI.

### CODE REVIEW

**Review by tatianacv — DISMISSED** [review]
Looks good.

**Comment by khatchad** [comment]
> Looks good.

Can you approve?

**Review by tatianacv — APPROVED** [review]

**Comment by tatianacv** [comment]
I can no longer see the logs in the build.

**Review by tatianacv — APPROVED** [review]

**Comment by khatchad** [comment]
> I can no longer see the logs in the build which is the intended behavior from the PR's description.

https://github.com/ponder-lab/ML/pull/49#issue-1786475692

**Pull request merged**
