### PR TITLE
Adding log for the dataflow sources

### PR DESCRIPTION
**Pull request by tatianacv**
Fix https://github.com/wala/ML/issues/66.

### CODE REVIEW

**Review by khatchad — APPROVED** [review]
LGTM.

**Review by tatianacv — COMMENTED** [review]
The log looks good.

**Comment by khatchad** [comment]
@tatianacv Can you also send this upstream?

**Comment by tatianacv** [comment]
> @tatianacv Can you also send this upstream?

Sounds good.

**Pull request merged**
